console.log("Yo what's up?")
console.log("So I heard you want to create your own Roblox is down screen or something.")
console.log("Well you're in luck, follow these steps.")
console.log("Step 1: Press CTRL + F (The search function).")
console.log("Step 2: Type title in the search function and change the title to your liking.")
console.log("Step 3: Type img in the search function and change the image to a vaild image.")
console.log("Step 4: Make sure you make the search bar roblox.com!")
console.log("You should be done! Please contact me you have questions! :D")