console.log("Yo what's up?")
console.log("So I heard you want to create your own Roblox is down screen or something.")
console.log("Well you're in luck, follow these steps.")
console.log("Step 1: Press CTRL + F (The search function).")
console.log("Step 2: Type <title> in the search function and change the title to your liking. It should look like <title>Test Name</title>.")
console.log("Step 3: Type img in the search function and go to the 3rd option and change the image to a vaild image.")
console.log("Step 4: Make sure you make the search bar roblox.com to make it more believable!")
console.log("Step 5 (Optional): If needed, adjust the size of the image. Type height in the search function and scroll down to .header img part and double click. Change the height to like 75% or 25% and if you need to adjust the width, type width in the search function and apply the width.")
console.log("You should be done! Please contact me you have questions! :D")