console.log("Yo what's up?")
console.log("So I heard you want to create your own Roblox is down screen or something.")
console.log("Well you're in luck, follow these steps.")
console.log("Step 1: Press CTRL + F (The search function).")
console.log("Step 2: Type <title> in the search function and change the title to your liking. It should look like <title>Test Name</title>.")
console.log("Step 3: Type img in the search function and go to the 3rd option and change the image to a vaild image.")
console.log("Step 4: Make sure you make the search bar roblox.com to make it more believable!")
console.log("Step 5 (Optional): If needed, adjust the size of the image. Go to the Sources section and go to style.css. Then change the height to your liking (default is 50%)")
console.log("Step 6 (Not recommended): If completely necessary (because height should automatically adjust the width to your liking) add width: 50%; to the line after or before the height line and change the number to your liking.")
console.log("You should be done! Please contact me you have questions! :D")
